In [2]:
# Numpy library
import numpy as np
# Creating a 1D array
array = np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [16]:
# Creating a 2D array
arr2 = np.array([[1,2,3,4,5,6],[1,2,4,3,5,6]])
print("1D array: ",arr2.shape)       # tells the dimensions/shape of the array
try:
    print("2D array: ",arr2.reshape(1,6))       # reshape the dimension of array
except ValueError:
    print("Error: unable to reshape array of size 12 to specified shape")
    print("no. of elements must be equal before and after reshaping of the array")

print(arr2.reshape(3,4))    # 3x4=12 elements


1D array:  (2, 6)
Error: unable to reshape array of size 12 to specified shape
no. of elements must be equal before and after reshaping of the array
[[1 2 3 4]
 [5 6 1 2]
 [4 3 5 6]]


In [19]:
# creating array with inbuilt functions
# arange() - Generates an array with evenly spaced values within a specified range.
arr1 = np.arange(0,10,2)           # array with values between 0 and 10 step of 2
print(arr1)
print(arr1.reshape(5,1))

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [22]:
# creating an array with all elements as ones and zeros

arr1 = np.ones((2,3))     # 2x3 matrix with all elements as 1
print(arr1)

arr2 = np.zeros((3,4))    # 3x4 matrix with all elements as 0
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# creating an identity matrix
np.eye(3)             #creates an identity matrix, which is a square matrix with 1s on the main diagonal and 0s elsewhere.


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr1 = np.array([[1,2],[3,4]])

print(arr1)
print(arr1.size)     # total no. of elements
print(arr1.dtype)    # type of array elements
print(arr1.itemsize) # size of elements in bytes
print(arr1.reshape(1,4))    # reshaping array (temprary)

[[1 2]
 [3 4]]
4
int64
8
[[1 2 3 4]]


In [37]:
# numpy Vectorized operations
# add, sub, mul, div 2 arrays

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [39]:
# univarsal functions - applied to all the elements in the array
# mathematical functions 

print(np.sqrt(arr2))     # squareroot of elements
print(np.exp(arr2))      # exponential of elements
print(np.log(arr2))       # natural logarithm of elements
print(np.sin(arr2))       # sine of elements
print(np.cos(arr2))       # cosine of elements 

# many more functions..............

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


In [48]:
# array slicing

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr1)

# extracting a row
print("first row: \n",arr1[0,:])     # extracting the row at 0th index
print("first 2 rows: \n",arr1[0:2,:])   # extracting the first 2 rows

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first row: 
 [1 2 3 4]
first 2 rows: 
 [[1 2 3 4]
 [5 6 7 8]]


In [49]:
# extracting a column
print("last column: \n",arr1[:,-1])       #extracting the column at last

last column: 
 [ 4  8 12]


In [69]:
# extracting subarray
print("subarray is :\n",arr1[1:,0:2])
print("subarray is :\n",arr1[0:2,2:])
print("subarray is :\n",arr1[1:,1:3])

subarray is :
 [[ 5  6]
 [ 9 10]]
subarray is :
 [[3 4]
 [7 8]]
subarray is :
 [[ 6  7]
 [10 11]]


In [74]:
# Statistical operations using numpy

data = np.array([1,2,3,4,5,6,7,8,9,10])

""" Mean - average value of an array 
               Mean= ∑X/N         """
mean = np.mean(data)
print(mean)

# Median - middle value in a sorted array. if number of elements is even, median is avg of the 2 mid element
median = np.median(data)
print(median)

"""Standard Deviation - measures the amount of variation in the dataset 
            std_dev = sqrt(∑((Xi - 𝜇)**2)/N)                    """
std_dev = np.std(data)
print(std_dev)

# Variance - Variance measures the spread of numbers in a dataset. It is the square of the standard deviation.
variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [87]:
# Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10,11])

print(data[(data>5) & (data<=7)])

[6 7]
